#! /bin/sh

case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon -n aesdsocket -S -- /usr/bin/aesdsocket -d
		;;
	stop)
		echo "Stopping aesdsocket"
		start-stop-daemon -n aesdsocket -K
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

